---
# tasks file for /home/fabian/workspace/digitalocean/playground/droplet-to-volume-attach/roles/blockstore_config
- name: set up custom directory for mount
  file:
    path: {{ mnt_dir }}
    state: directory

- name: format block device to xfs
  filesystem:
    fstype: xfs
    dev: {{ device }}

- name: mount new block storage file system
  mount:
    state: mounted
    fstype: xfs
    name: {{ mnt_dir }}
    src: {{ device }}
    opts: "discard,defaults"

- name: set up system user
  user:
    name: {{ mnt_owner }}
    state: present

- name: change directory ownership and permissions
  file:
    path: {{ mnt_dir }}
    state: directory
    owner: {{ mnt_owner }}
    group: {{ mnt_group }}
